#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scalacheck
Version  : 1.13.5
Release  : 1
URL      : https://github.com/rickynils/scalacheck/archive/1.13.5.tar.gz
Source0  : https://github.com/rickynils/scalacheck/archive/1.13.5.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/scalacheck/scalacheck_2.12/1.13.5/scalacheck_2.12-1.13.5.jar
Source2  : https://repo.maven.apache.org/maven2/org/scalacheck/scalacheck_2.12/1.13.5/scalacheck_2.12-1.13.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-scalacheck-data = %{version}-%{release}

%description
# ScalaCheck
[![Build Status](https://secure.travis-ci.org/rickynils/scalacheck.png?branch=master)](http://travis-ci.org/rickynils/scalacheck)

%package data
Summary: data components for the mvn-scalacheck package.
Group: Data

%description data
data components for the mvn-scalacheck package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalacheck/scalacheck_2.12/1.13.5
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scalacheck/scalacheck_2.12/1.13.5/scalacheck_2.12-1.13.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalacheck/scalacheck_2.12/1.13.5
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/scalacheck/scalacheck_2.12/1.13.5/scalacheck_2.12-1.13.5.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scalacheck/scalacheck_2.12/1.13.5/scalacheck_2.12-1.13.5.jar
/usr/share/java/.m2/repository/org/scalacheck/scalacheck_2.12/1.13.5/scalacheck_2.12-1.13.5.pom
